* June 2026
** 6 June 2026
*** Call for abstract
- Add "ICAPST Awards" in a orange box between "journal publication" and "important dates" add following detials in this section:
  - ICAPST Best Research Paper Award
  - Young Scientist Award
  - Women in Science Excellence Award
  - Best Oral Presentation Award
  - Best Poster Presentation Award
  - Best Master's Student Presentation Award
Similar to important dates, also link "ICAPST Awards" at home page after important dates.

*** Invited spearkers 
- add "Dr. Anshu Sharma, Department of Applied Sciences & Humanities, Central University of Haryana, Mahendergarh, Haryana"
Use photo from advisory committee
- add "Prof. Boris V. Balakin, Western Norway University of Applied Sciences, Norway" 
  Use photo from advisory committee
*** Home Page
- before download flyer add an organge box "Conference Attractions"
add a box and add these bullet point in that box
"(i) Interdisciplinary Scientific Sessions covering Physics, Chemistry, Materials Science, Nanotechnology, Energy, Environment, and Emerging Technologies. Keynote and Invited Lectures on cutting-edge research and future technological trends. (ii) Abstract Publication in Conference Proceedings. (iii) Selected papers may be recommended for publication in Scopus/SCI-indexed journals/proceedings: Solar Compass  (Elsevier), Springer Proceedings in Physics, AIP conference proceedings. (iv) ICAPST Awards (v) Experience the rich heritage of Jaipur, known as the Pink City."
*** Registration
- Guidelines, add this point "Foreign students/scholars may request a fee concession if they face difficulty in paying the conference fee."
- Add a organce box before Guidelines "Mode of Payment" 
- Make a table with following points: 
  1. Beneficiary Name:	CONVENER ICAPST UOR JAIPUR
  2. Account No:	674701702992
  3. Bank:	ICICI, Univeristy of Rajasthan Campus
  4. IFSC	ICIC0006747
  5. SWIFT code: ICICINBBNRI
- add this text after this table: "Upload your payment receipt and transaction details to complete your registration." Here we need to make a google form receipt option.
** 7 June
*** Speakers: Please add following 
- Dr. Purushottam Soni,Chemical Engineering, Marian University, USA
- Dr. Samantha Wijewardane, University of South Florida, USA
- Dr. Ashish Kumar Meena, Assistant Professor, Physics Department, IISc Bengaluru, India
- Dr. Lata Panwar, Department of Physics, IIT Jodhpur, India.
- Phots uploaded
** 9 June
*** Registration
- add this line at bottom for fee structure as star "Special concessional Conference Day Tickets are available for UG and PG students presenting their research papers. Students interested in this opportunity may submit their request to ICAPST2026@gmail.com"

* May 2026
** 2 May (completed)
- Updated KK in invited speakers.
- Updated a test file, where people can submit their abstract. Still need to update, so did not gave link at Abstract tab yet.
** 4 May (completed)
*** Call for Abstract
1. Abstract limit minimum 200 and maximum 250 should be checked
2. Country code should be manual 
3. Ask full detials of Second author and third author and rest in othe big box. 
4. Upload file limit 1 MB
5. Submission Id should include conference track 
*** Markquee
1. Remove icon
2. Text colour Dark Green
3. Remove - after scopus

** 7 May (completed)
- Added an [[docs/email1.html][email draft]]
** 8 May (completed)
- Added Open Graph meta tags or social media previews

** 11 May (completed)
*** Home
- Add "Reach Us" from Others, after "Sponsers are welcome"
- Keep Reach Us in Others also
*** Corrections in "Reach Us"
- General Query change email : ICAPST2026@gmail.com
- Submission & Registration, add email: info.icapst@gmail.com
- Visa & Travel Assistance, add email: info.icapst@gmail.com

** 12 May (completed)
*** Call for Abstract
- submission guidline: word limit is changed 200
- abstract templete is changed and uploaded

** 17 May (completed)
- Updated new email icapst.info@gmail.com

* April 2026
** 02 April (completed)
*** Advisory committee "Dr. Narendra K Soni
Director R & D, NTPC Ltd." change "Dr. Narendra K Soni
Sr. Manager, NTPC Ltd."
*** Accomodation
1. Option 1: add "Tariff: Approximately ₹1500 per room per night"
2. Option 2: add "Tariff: Approximately ₹800 - ₹1000 per room per night"
3. Option 3: add "Tariff Mid-range hotels: $25–$50 per night
& Premium hotels: $50–$100+ per night"
** 12 April (completed)
*** Speakers: Add follwoings
1. "Prof. S.K. Samdarshi, Department of Energy Engineering, Central University, Rachi, Jharkhand, India"
2. "Dr. Harsh Soni, School of Physical Sciences, IIT Mandi, Himachal Pradesh, India."
3. "Prof. Ramesh L. Gardas, Department of Chemistry, IIT Madras, Chennai, Tamil Nadu, India"
4. "Dr. Komal Bapna, Sr. Scientist, CSIR - National Physical Laboratory, New Delhi, India"
5. "Prof. Patrick Oyirwoth Abedigamba, Head, Department of Physics, Kyambogo University, Uganda"
-Photo of 4th is uploaded, rest are in advisory committee. 
** 17 April (completed)
*** Speaker
1. replace Photo to Komal Bapna, New file name Dr_Komal, Please remove the old one. 

** 19 April (completed)
*** Call for papers
1. Submission guidelines, replace by these new ones:
   - Word limit: 200–250 words.
   - The abstract should clearly state the objectives, methodology, key results, and major conclusions of the research.
   - Submissions must be original and free from plagiarism (similarity index below 10%).
   - Authors are required to select the appropriate conference track at the time of submission.
   - All submissions will be reviewed based on: originality, novelty, technical quality and relevance to conference themes.
   - Accepted abstracts will be invited for: Oral or Poster presentation
   - Detailed presentation instructions will be shared after acceptance
   - After abstract acceptance a full-length paper can be submitted.
   - A full paper submission is not mandatory to present a paper or attend ICAPST.
   - At least one author must register and present the paper at the conference for it to be included in the ICAPST proceedings and considered for journal publication recommendation. 
2. Journal Publication, replace first line "Authors can submit full manuscript in conference-aligned journals after conference." by "Selected papers may be recommended for further peer review process in the partnered journals.”
3. Abstract Template, change "Download Abstract Template". The formate is in uploaded file name "Abstract_Template_ICAPST.doc" Link this file in doc, pdf and linex format.
4. Poster Template, change the pop-up "It will be avaliable after 15 July"
5. Important dates:
   - "Abstract Submission Deadline: Submit by 15 August 2026" change "Abstract Submission Deadline: Submit by 1 July 2026"
   - "Acceptance Notification: will be communicated by 25 August 2026" change "Acceptance Notification: will be communicated by 15 July 2026" add "Full-length Paper Submission Deadline: Submit by 15 August 2026"
*** Home
1. Make a orange box after venue and write "Importance Dates" either link this or repeate the same information given in call for papers. 

** 24 April (completed)
**** "Selected papers will be recommended for publication in Scopus- and SCI-indexed journals in collaboration with ICAPST" Please add this line, it should scroll on the top of site page.
 

* March 2026 updates (completed)
** 25 March 2026 (completed)
*** Home page
1. ✅ "Be part of Advancing Knowledge, Inspiring Innovation: Join ICAPST 2026" Add this tag line after Welcome at home page and before download flyer 
2. ✅ link flyer, file name ICAPST_flyer
*** Call for abstract
1. ✅ Abstact templete- link a file that open with text "Abstract sumbmission will open shortly" 
*** Speakers
1. ✅ add a yellow box in last write "More to be Announced"
*** About us
1. ❌ Department link is not working, please resolve *(It is working, tested with my BSNL data and University line)*
*** Others
1. ✅ "Air, Rail and Road Connectivity" Dark blue bold. 

** 27 March 2026 (completed)
*** Call for Abstract 
**** Submission guideline
- Add two more blue box 
  1. ✅ In one write "Submission by Speakers", add a pop-up "Please email your abstract at icapst2026@gmail.com"
  2. ✅ In other write "Submission by Presenters" add a pop-up "Submission link will open shortly"
** 28 March 2026 (completed)
*** Registration
1. Guidelines: "The registration fee covers a conference kit, access to domain-specific sessions, a presentation/participation certificate, and food coupons during the conference."
Change this "The registration fee covers a conference kit, access to domain-specific sessions and a presentation/participation certificate.
It also includes food coupons, with lunch provided for all three days of the conference."
*** ✅ Following change made, as I understood:
- The registration fee covers a conference kit, access to domain-specific sessions and a presentation/participation certificate.
- It also includes food coupons, with lunch provided for all three days of the conference.
ok
*** ✅ Others
1. change "Transportation" to "Travel Information"
2. Visa Information "If you need urgent help, feel free to reach out to the Transportation Team." change "If you need urgent help, feel free to reach out to the Visa and Travel Assistance Team"
- I have done one more thing, if you do not like, I can revert. Now if anyone clicks on logo and "ICAPST 2026" on left up corner, it takes you back to home page.
*** response 
1. all changes are good

** 29 March 2026 (completed)
*** ✅ Advisory Committee 
1. "Amesh" Correct is "Ambesh"
*** ✅ Others
1. "Travel" in Blue box change "Visa & Travel"
*** Advisory Committee
1. add "Prof. Manikandan Palanichamy, Associate Professor, Department of Engineering at Østfold University College." After Prof. Maarteen
2. Photo file "Prof_Manikandan"
** 30 March 2026 (completed)
*** Advisory Committee
1. Add in National "Dr. H. L. Swami, Scientific Officer-F, IPR, Gandhinagar, Gujarat" 
